#! /bin/bash

sxhkd &
picom &
setxkbmap -option grp:caps_toggle us,ru &
xsetroot -cursor_name left_ptr &
feh --bg-scale ~/.config/bspwm/wallpaper.jpg
polybar &

firefox &
telegram-desktop &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
flameshot &

bspc monitor HDMI-A-0 -d 1 3 4 5 6 7
bspc monitor HDMI-A-1 -d 2

##Main settings
bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true 
bspc config focus_follows_pointer true

##Color theme (based on Adapta Dark colors)
bspc config focused_border_color "#00bcd4"
bspc config normal_border_color "#2E3134"
bspc config presel_feedback_color "#4B4F51"

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
