#! /bin/bash

sxhkd &
picom &
polkitt
setxkbmap -option grp:alt_shift_toggle us,ru &                                    
xsetroot -cursor_name left_ptr & 
~/.config/bspwm/scripts/launch_polybar.sh &
feh --bg-scale ~/.config/bspwm/wallpaper/00000.jpeg 

firefox &
telegram-desktop &
spotify-launcher &
discord &
steam &

bspc rule -a Discord desktop='^1'
bspc rule -a firefox desktop='^3'
bspc rule -a steam desktop='^3'
bspc rule -a spotify-launcher desktop='^2'

bspc monitor DisplayPort-1 -d 1
bspc monitor HDMI-A-0 -d 2
bspc monitor HDMI-A-1 -d 3 4 5 6
bspc monitor DisplayPort-1 -s HDMI-A-0
bspc monitor HDMI-A-0 -s HDMI-A-1

##Main settings
bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true
bspc config focus_follows_pointer true

##Color theme (based on Adapta Dark colors)
bspc config focused_border_color "#00bcd4"
bspc config normal_border_color "#2E3134"
bspc config presel_feedback_color "#4B4F51"