font:
  size: 10.0
  bold:
    family: "JetBrainsMono"
    style: "Bold"
  normal:
    family: "JetBrainsMono"
    style: "Bold"

scrolling:
  history: 100

window:
  opacity: 0.8
  padding:
    x: 15
    y: 15
